project:
  type: book
  output-dir: docs


book:
  title: "Perangkat"
  author: "Risnandar H. Sahido"
  sidebar: 
    style: docked
    background: primary
  date: "1/12/2026"
  twitter-card: true
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Kelas XI"
      chapters: 
        - CapaianPembelajaran.qmd
        - prota.qmd
        - promes.qmd
        - jadwal.qmd
        - modulajar.qmd
    - part: "Kelas XII"
      chapters: 
        - CapaianPembelajaranXII.qmd
        - protaXII.qmd
        - promesXII.qmd
        - jadwalXII.qmd
        - modulajarXII.qmd
    - summary.qmd
    - references.qmd
  page-footer: 
    left: "Copyright 2026, Risnandar H. Sahido" 
    right: 
      - icon: github
        href: https://github.com/nandarmath
      - icon: twitter 
        href: https://twitter.com/risnandar88
      - icon: instagram
        href: https://instagram.com/nandar_88
    



bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    toc-depth: 3
    toc-title: "Daftar Konten"
    number-depth: 3
    fontsize: "14"
  pdf:
    documentclass: scrreprt
    number-depth: 3
    pdf-engine: pdflatex
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex

comments:
  hypothesis: true

editor: visual

